x-params:
    - &common
        environment:
            XDEBUG_MODE: coverage
        volumes:
            - ./src/:/app/src:ro
            - ./tests/:/app/tests:ro
            - ./composer.json/:/app/composer.json:ro
            - ./phpunit.xml.dist/:/app/phpunit.xml.dist:ro
            - /app/tests/Bundle/App/var # anonymous writable volume for cache/logs 
        command:
            - sh
            - -c
            - 'composer install && vendor/bin/simple-phpunit --coverage-text'
            
# To run test just exec e.g. 'docker compose run --rm php8.1'
services:
    php8.1:
        build:
            context: .
            target: php
            args:
                PHP_VERSION: 8.1
        <<: *common
            
    php8.2:
        build:
            context: .
            target: php
            args:
                PHP_VERSION: 8.2
        <<: *common
            
    php8.3:
        build:
            context: .
            target: php
            args:
                PHP_VERSION: 8.3
        <<: *common
